# test/docker-compose.yml
version: "3.9"
services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --bind redis --port 6379 --save 20 1 --loglevel warning
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - webnet
  live-server-test:
    image: kltest-live-server:latest
    container_name: kltest-live-server
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        node_env: development
        exposed_port: 8000
        npm_private_repo_token: ${NODE_AUTH_TOKEN}
        redis_host: redis
        redis_port: 6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links: 
     - redis:redis 
    networks:
      - webnet
networks:
  webnet: