FROM node:14
WORKDIR /usr/src/app
COPY ./package*.json ./
COPY ./src ./src
COPY ./tsconfig.json .
COPY ./node_modules ./node_modules
COPY ./types ./types
COPY ./dist ./dist


ENV PORT=8080
EXPOSE 8080
CMD [ "npm", "start" ]
